"""
Generates data/sample_tickets.xlsx — the ML training file.

The trainer (src/ml/trainer.py) requires:
  - sheet name : "Tickets"
  - columns    : Summary, Description, Category

This script creates 3 labelled examples for every category across all 7 teams
(48 categories × 3 = 144 rows), giving the TF-IDF + LogisticRegression model
enough signal to learn each class before stratified train/test split.

Run: python scripts/generate_training_data.py
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

# ---------------------------------------------------------------------------
# Training rows: (Summary, Description, Category)
# Category must exactly match a key in TEAM_CATEGORIES / the classifier labels.
# ---------------------------------------------------------------------------
ROWS = [
    # ── Testing Team ─────────────────────────────────────────────────────────
    ("Test case failed on login module",
     "Automated test case for the login module failed after the latest deployment. Assertion error on expected vs actual token value.",
     "Test case failure"),
    ("Unit test returning incorrect result",
     "Unit test for order processing returned wrong status code. Test needs to be updated to match new API contract.",
     "Test case failure"),
    ("Functional test failure in payment flow",
     "Test case for payment gateway returned 500 instead of 200. Defect logged in Jira for developer review.",
     "Test case failure"),
    ("Integration test failing after API contract change",
     "Integration test suite failing after upstream API changed its response schema. Contract tests need to be updated.",
     "Test case failure"),
    ("Test case not covering new business logic branch",
     "New conditional branch added in claims processing is not covered by any existing test case. Coverage gap identified.",
     "Test case failure"),

    ("Regression suite blocked by environment issue",
     "Regression test suite cannot run because the test environment database is not reachable from the test runner.",
     "Regression test blocked"),
    ("Nightly regression blocked after config change",
     "Overnight regression job failed at startup. Environment configuration file was overwritten during a release.",
     "Regression test blocked"),
    ("Regression pipeline failing at smoke test stage",
     "Smoke test gate in the regression pipeline is failing. Root cause is a missing environment variable in the test config.",
     "Regression test blocked"),
    ("Regression blocked due to data dependency failure",
     "Regression suite cannot proceed because a upstream data seeding step failed. Test data pipeline must run first.",
     "Regression test blocked"),
    ("Regression environment certificate expired",
     "Regression test environment SSL certificate expired blocking all HTTPS-based test scenarios from executing.",
     "Regression test blocked"),

    ("UAT environment returning 502 errors",
     "Business users cannot access the UAT environment. Load balancer is returning 502 Bad Gateway for all requests.",
     "UAT environment issue"),
    ("UAT database out of sync with production",
     "UAT environment is running on stale data. Last data refresh was 3 weeks ago causing test failures.",
     "UAT environment issue"),
    ("UAT application server not starting",
     "Application server in the UAT environment failed to start after last night's deployment. Logs show a port conflict.",
     "UAT environment issue"),
    ("UAT email service not sending notifications",
     "Email notification service in UAT is not sending messages. SMTP relay settings differ from production configuration.",
     "UAT environment issue"),
    ("UAT environment running wrong application version",
     "UAT environment was deployed with last sprint build instead of current release candidate. Redeployment needed.",
     "UAT environment issue"),

    ("Selenium script broken after UI change",
     "Automation script for the checkout flow broke after a UI refactor. Element locator IDs changed in the new build.",
     "Automation script error"),
    ("Test automation framework throwing null pointer",
     "Automation framework throws a NullPointerException during test setup. Suspected issue with dependency injection.",
     "Automation script error"),
    ("Robot Framework keyword failing on assertions",
     "Custom keyword in Robot Framework test suite is returning unexpected values after library upgrade.",
     "Automation script error"),
    ("Cypress test failing due to timing issue",
     "Cypress end-to-end test failing intermittently due to race condition. Explicit wait needs to be added.",
     "Automation script error"),
    ("Automation script not compatible with new browser version",
     "Automation script using deprecated WebDriver API that is no longer supported in the latest browser version.",
     "Automation script error"),

    ("Test data not available for regression run",
     "Test execution blocked because the required test data set was not loaded into the test environment database.",
     "Test data missing"),
    ("Missing test accounts in UAT environment",
     "UAT test users were deleted during last environment refresh. New accounts need to be created before testing resumes.",
     "Test data missing"),
    ("Reference data absent from test schema",
     "Product reference table is empty in the test schema. Seeding script needs to be re-executed.",
     "Test data missing"),
    ("Test data masking not applied in lower environment",
     "Production data copy in test environment contains real PII. Data masking script must be run before testing.",
     "Test data missing"),
    ("Test environment database out of date",
     "Test database was not refreshed this sprint. Test cases are failing because required records do not exist.",
     "Test data missing"),

    ("QA sign-off pending for release 4.2",
     "QA team has not yet signed off on release 4.2. Three critical test cases are still in progress.",
     "QA sign-off pending"),
    ("Release blocked waiting for QA approval",
     "Deployment is on hold pending QA sign-off. Two defects raised during final regression are under review.",
     "QA sign-off pending"),
    ("QA checklist incomplete for sprint close",
     "Sprint closure blocked because QA sign-off checklist has two open items related to API boundary tests.",
     "QA sign-off pending"),
    ("QA team waiting on developer fix before final sign-off",
     "QA has completed all test cases but is awaiting a developer patch for one critical defect before sign-off.",
     "QA sign-off pending"),
    ("UAT sign-off delayed by business stakeholder availability",
     "Business stakeholder is unavailable to provide UAT sign-off. Release date may need to be pushed.",
     "QA sign-off pending"),

    ("Performance test failing under 500 concurrent users",
     "Load test scenario with 500 virtual users is causing the application to time out. Response time exceeds 10 seconds.",
     "Performance test failure"),
    ("Throughput degraded in stress test run",
     "Stress test results show throughput dropped by 60% at 300 concurrent users compared to last sprint baseline.",
     "Performance test failure"),
    ("Memory leak detected during soak test",
     "24-hour soak test revealed a memory leak in the session management component. Heap usage grows 2 MB per minute.",
     "Performance test failure"),
    ("API response time exceeds 3 second SLA under load",
     "Claims API response time degrades to 8 seconds under 200 concurrent users. Performance target is 3 seconds.",
     "Performance test failure"),
    ("Database query slowdown identified in performance test",
     "Performance test identified a single unindexed query responsible for 70% of total response time under load.",
     "Performance test failure"),

    # ── EDI Team ─────────────────────────────────────────────────────────────
    ("EDI 837 transaction rejected by payer",
     "Outbound 837P transaction was rejected by the payer clearinghouse. Error code PR-96 indicates missing attending provider NPI.",
     "EDI transaction error"),
    ("Inbound EDI file not processed",
     "Inbound EDI file from trading partner has been sitting in the inbound queue for 6 hours without processing.",
     "EDI transaction error"),
    ("EDI batch job terminated mid-processing",
     "EDI processing batch job terminated with exit code 1. Partial records written to staging. Full rollback initiated.",
     "EDI transaction error"),
    ("EDI translator throwing parse error on segment",
     "EDI translator is throwing a parse error on the ST segment of incoming 270 files. Delimiter mismatch detected.",
     "EDI transaction error"),
    ("EDI job failed due to invalid interchange envelope",
     "EDI processing job failed because the ISA/IEA interchange envelope control numbers do not match.",
     "EDI transaction error"),

    ("835 remittance file missing from daily drop",
     "Expected 835 remittance file from Blue Cross has not arrived in the SFTP drop folder. SLA window exceeded.",
     "835 file not received"),
    ("835 file delayed from trading partner",
     "Trading partner confirmed the 835 file was sent but it has not landed in our SFTP directory. Network trace requested.",
     "835 file not received"),
    ("835 not received after payer reprocessing",
     "Payer initiated a claim reprocessing event but the corresponding 835 file has not been delivered to our system.",
     "835 file not received"),
    ("835 file arrived with zero payment records",
     "835 remittance file received but contains no payment detail records. Payer confirmed the file was sent correctly.",
     "835 file not received"),
    ("835 remittance not posted — file not in system",
     "Finance team reports remittance was not posted. Investigation shows 835 file never arrived in EDI inbox.",
     "835 file not received"),

    ("837 claim rejected at clearinghouse",
     "837 professional claim file was rejected at the clearinghouse gateway. Control number ISA13 flagged as duplicate.",
     "837 claim rejection"),
    ("837 institutional claim failure",
     "837I file rejected by payer. Loop 2300 CLM05 service facility location code is invalid for the plan type.",
     "837 claim rejection"),
    ("837 dental claim not accepted",
     "837D file returned with TA1 rejection. ISA authorization information qualifier does not match trading partner agreement.",
     "837 claim rejection"),
    ("837 claim missing required NPI in billing loop",
     "837P claim rejected because the billing provider NPI is absent from loop 2010AA. Sender must include NPI.",
     "837 claim rejection"),
    ("837 file rejected — invalid transaction set identifier",
     "837 file rejected at interchange. ST01 transaction set identifier code does not match the agreed claim type.",
     "837 claim rejection"),

    ("SFTP connection to trading partner failing",
     "SFTP connection to partner endpoint times out after 30 seconds. SSH key fingerprint changed on remote server.",
     "EDI partner connectivity"),
    ("AS2 transmission failure to clearinghouse",
     "AS2 message delivery to clearinghouse failed with MDN error. SSL certificate on partner endpoint has expired.",
     "EDI partner connectivity"),
    ("FTP drop folder not accessible from EDI server",
     "EDI server cannot mount the partner FTP drop folder. Firewall rule was updated and blocked the required port.",
     "EDI partner connectivity"),
    ("Trading partner VAN unreachable",
     "Value-added network connection to trading partner is down. EDI files are queuing locally with no delivery confirmation.",
     "EDI partner connectivity"),
    ("EDI partner endpoint returning connection refused",
     "Outbound EDI delivery to partner is failing with connection refused. Partner IT confirmed a firewall change on their side.",
     "EDI partner connectivity"),

    ("HIPAA 5010 validation errors in 837P file",
     "837P file failed HIPAA 5010 validation. Segment ST03 implementation convention reference is missing.",
     "HIPAA validation failure"),
    ("X12 file failing HIPAA compliance checks",
     "Inbound X12 file has multiple HIPAA compliance errors. GS08 version identifier does not match the agreed standard.",
     "HIPAA validation failure"),
    ("HIPAA rule violation in 277 response",
     "277CA response contains data elements that violate HIPAA minimum necessary standard. Privacy review required.",
     "HIPAA validation failure"),
    ("HIPAA transaction set not acknowledged within window",
     "HIPAA transaction sets sent yesterday have not received compliant acknowledgement within the required timeframe.",
     "HIPAA validation failure"),
    ("HIPAA segment count mismatch in IEA trailer",
     "IEA segment count in the interchange trailer does not match the actual number of functional groups in the file.",
     "HIPAA validation failure"),

    ("EDI map not translating GS segment correctly",
     "EDI mapping is producing incorrect values in the GS04 date element. Map definition needs to be updated.",
     "EDI mapping issue"),
    ("Crosswalk table out of sync with partner spec",
     "Member ID crosswalk table has stale entries causing 270 eligibility transactions to fail at partner validation.",
     "EDI mapping issue"),
    ("Loop 2110 data elements mapped to wrong segment",
     "Loop 2110 in the 835 inbound map is writing service adjustment codes to the wrong data element position.",
     "EDI mapping issue"),
    ("EDI segment qualifier code incorrect in map",
     "Qualifier code in the N3 address segment of the 837 map is hardcoded to wrong value. Partner spec update needed.",
     "EDI mapping issue"),
    ("EDI map not handling optional segments correctly",
     "EDI translation map is rejecting files that omit optional segments. Map logic must allow conditional segments.",
     "EDI mapping issue"),

    ("997 acknowledgement not returned within SLA",
     "Trading partner has not sent a 997 functional acknowledgement within the agreed 2-hour window.",
     "Acknowledgement not received"),
    ("999 acknowledgement missing from payer",
     "999 implementation acknowledgement from payer has not been received after 4 hours. Escalation initiated.",
     "Acknowledgement not received"),
    ("TA1 interchange acknowledgement absent",
     "TA1 interchange acknowledgement not received after sending a batch 837. Partner technical contact notified.",
     "Acknowledgement not received"),
    ("Duplicate 997 acknowledgement received causing confusion",
     "System received two 997 acknowledgements for the same transaction set. Duplicate processing logic needs review.",
     "Acknowledgement not received"),
    ("Acknowledgement received with AK5 rejection code",
     "997 acknowledgement returned with AK5 reject code R indicating the transaction set was not accepted by payer.",
     "Acknowledgement not received"),

    ("New trading partner onboarding setup required",
     "New trading partner needs to be configured in the EDI system. ISA qualifier codes and test file exchange required.",
     "Trading partner setup"),
    ("Partner specification update for 5010 transition",
     "Trading partner issued updated 5010 implementation guide. Map definitions and companion documents need revision.",
     "Trading partner setup"),
    ("Trading partner test connectivity not established",
     "Initial test connectivity with new payer partner has not been established. Credentials and endpoint details pending.",
     "Trading partner setup"),
    ("Trading partner ISA qualifier codes need updating",
     "Existing trading partner changed their ISA05 and ISA07 qualifier codes. EDI system configuration must be updated.",
     "Trading partner setup"),
    ("New payer added requiring EDI enrollment form",
     "New payer requires completion of an EDI enrollment form and submission of a test file before go-live approval.",
     "Trading partner setup"),

    # ── BizTalk Team ─────────────────────────────────────────────────────────
    ("BizTalk orchestration instance faulted",
     "BizTalk orchestration instance is in faulted state. Dehydration failed due to missing correlation token.",
     "BizTalk orchestration failure"),
    ("BizTalk orchestration suspended during processing",
     "An orchestration instance suspended mid-flow after an unhandled SOAP fault from a downstream web service.",
     "BizTalk orchestration failure"),
    ("BizTalk host crashed during orchestration run",
     "BizTalk host instance crashed during a long-running orchestration. Windows event log shows memory access violation.",
     "BizTalk orchestration failure"),
    ("BizTalk orchestration looping indefinitely",
     "An orchestration instance is caught in an infinite loop. CPU usage on BizTalk server is at 100%.",
     "BizTalk orchestration failure"),
    ("BizTalk orchestration not resuming after dehydration",
     "Dehydrated orchestration instance failed to rehydrate after the timer expired. Instance stuck in dehydrated state.",
     "BizTalk orchestration failure"),

    ("Message stuck in BizTalk receive location",
     "Inbound message has been in the receive location queue for 8 hours. Receive host is running but not picking up.",
     "Message routing error"),
    ("BizTalk router sending to wrong send port",
     "Promoted property-based routing is sending messages to the wrong send port. Filter expression needs correction.",
     "Message routing error"),
    ("Message not routed after schema promotion",
     "Message routing failed after a schema property was promoted. No matching subscription found for the new value.",
     "Message routing error"),
    ("BizTalk content-based routing producing no output",
     "Content-based routing orchestration receives messages but produces no output. Decision shape logic has a gap.",
     "Message routing error"),
    ("Message routed to wrong application in BizTalk",
     "Inbound message is being routed to the wrong BizTalk application. Promoted property value collision detected.",
     "Message routing error"),

    ("BizTalk pipeline component throwing exception",
     "Custom pipeline component in the receive pipeline is throwing a SerializationException on malformed input.",
     "BizTalk pipeline exception"),
    ("Decode stage failure in BizTalk pipeline",
     "BizTalk receive pipeline failing at the decode stage. MIME decoder is rejecting non-standard content encoding.",
     "BizTalk pipeline exception"),
    ("Validate stage rejecting valid schema",
     "BizTalk pipeline validate stage is rejecting messages that conform to the deployed schema. Cache refresh needed.",
     "BizTalk pipeline exception"),
    ("BizTalk assembler stage producing malformed output",
     "XML assembler in the send pipeline is producing malformed XML. Envelope schema has incorrect root node definition.",
     "BizTalk pipeline exception"),
    ("Custom pipeline component causing memory leak",
     "A custom pipeline component is not disposing unmanaged resources causing gradual memory increase on the host.",
     "BizTalk pipeline exception"),

    ("Multiple messages suspended in BizTalk admin",
     "BizTalk admin console shows 47 suspended messages. All relate to a single send port that went offline.",
     "Suspended message in BizTalk"),
    ("Suspended messages after host restart",
     "After restarting the BizTalk host, 12 messages remain in suspended state. Resume operation returning error.",
     "Suspended message in BizTalk"),
    ("BizTalk suspended message queue growing",
     "Suspended message count has grown from 5 to 200 in 30 minutes. Root cause is an unreachable SQL adapter endpoint.",
     "Suspended message in BizTalk"),
    ("Suspended messages cannot be resumed in BizTalk",
     "Attempting to resume suspended messages in BizTalk admin returns error. Orchestration instance is in invalid state.",
     "Suspended message in BizTalk"),
    ("BizTalk message suspended due to port being offline",
     "Send port went offline due to destination being unreachable. All messages for that port are now suspended.",
     "Suspended message in BizTalk"),

    ("WCF-SQL adapter not connecting to database",
     "BizTalk WCF-SQL adapter cannot connect to the target database. Connection string in adapter configuration is outdated.",
     "BizTalk adapter configuration"),
    ("FILE adapter send port creating zero-byte files",
     "FILE adapter send port is creating zero-byte files in the output folder. Handler credentials need to be updated.",
     "BizTalk adapter configuration"),
    ("HTTP adapter returning 401 on outbound calls",
     "BizTalk HTTP adapter returns 401 Unauthorized on outbound sends. Service account password was recently changed.",
     "BizTalk adapter configuration"),
    ("BizTalk MSMQ adapter dropping messages silently",
     "MSMQ adapter is not delivering messages and no errors are logged. Queue permissions may be blocking the service account.",
     "BizTalk adapter configuration"),
    ("BizTalk FTP adapter not polling remote directory",
     "FTP receive adapter stopped polling the remote directory after a password change. Handler needs to be reconfigured.",
     "BizTalk adapter configuration"),

    ("XML validation failure in BizTalk receive pipeline",
     "BizTalk receive pipeline failing schema validation for inbound XML. Namespace prefix differs from deployed schema.",
     "Schema validation error"),
    ("BizTalk schema resolver unable to match document",
     "Schema resolver cannot find matching schema for inbound document. Document type property not promoted correctly.",
     "Schema validation error"),
    ("Flat file disassembler rejecting inbound file",
     "BizTalk flat file disassembler rejecting file due to header delimiter mismatch. Schema delimiter config needs update.",
     "Schema validation error"),
    ("Namespace mismatch causing schema validation failure",
     "Inbound XML message namespace does not match the deployed BizTalk schema. Partner changed namespace without notice.",
     "Schema validation error"),
    ("BizTalk schema version conflict after deployment",
     "Two versions of the same schema are deployed in BizTalk causing ambiguous resolution and validation failures.",
     "Schema validation error"),

    ("BizTalk host instance not starting",
     "BizTalk host instance failed to start after server reboot. Event log shows SSO service dependency not ready.",
     "BizTalk host instance down"),
    ("All BizTalk hosts stopped unexpectedly",
     "All BizTalk host instances stopped simultaneously. Windows service account password expired triggering service stop.",
     "BizTalk host instance down"),
    ("BizTalk isolated host unavailable for IIS",
     "IIS-hosted BizTalk receive locations are unavailable. Isolated host instance stopped and cannot be restarted.",
     "BizTalk host instance down"),
    ("BizTalk host instance crashing repeatedly on startup",
     "BizTalk host instance crashes within 2 minutes of starting. Corrupt orchestration assembly suspected.",
     "BizTalk host instance down"),
    ("BizTalk tracking host not processing data",
     "BizTalk tracking host instance is stopped causing tracking data to not be written to the DTA database.",
     "BizTalk host instance down"),

    ("BizTalk tracking database growing rapidly",
     "BizTalk tracking (BizTalkDTADb) database has grown by 20 GB in one week. DTA purge job is not running.",
     "Tracking database issue"),
    ("Tracking data not visible in HAT tool",
     "Health and Activity Tracking tool shows no tracked messages. DTA database write is failing due to permissions.",
     "Tracking database issue"),
    ("BizTalk message tracking causing performance issues",
     "Enabling message body tracking on a high-throughput send port is causing SQL blocking. Tracking should be disabled.",
     "Tracking database issue"),
    ("BizTalk DTA archive job not running",
     "DTA archive and purge job has not run in 2 weeks. Tracking database is consuming excessive disk space.",
     "Tracking database issue"),
    ("Tracked message details not visible in admin console",
     "BizTalk administration console shows no tracked message details for last 24 hours. Tracking query timeout suspected.",
     "Tracking database issue"),

    # ── Database Team ─────────────────────────────────────────────────────────
    ("Application cannot connect to SQL Server",
     "Application is throwing SqlException: connection timeout expired. SQL Server connectivity lost from app server.",
     "Database connection timeout"),
    ("Database connection pool exhausted",
     "All connections in the ADO.NET connection pool are in use. Application requests are queuing and timing out.",
     "Database connection timeout"),
    ("Intermittent database connection drops",
     "Application logs show intermittent connection resets to the primary database every 15 minutes.",
     "Database connection timeout"),
    ("JDBC connection timeout on application server",
     "Java application server reporting JDBC connection timeout to Oracle database. Connection pool settings need tuning.",
     "Database connection timeout"),
    ("Database connection failing after network change",
     "Application cannot reach database server after network reconfiguration. New IP address not updated in config.",
     "Database connection timeout"),

    ("Report query running for over 30 minutes",
     "Monthly claims summary report query has been running for 35 minutes. Execution plan shows full table scan.",
     "Slow query performance"),
    ("Dashboard loading slowly due to unindexed join",
     "Dashboard page takes 45 seconds to load. SQL Profiler identified a missing index on the member eligibility join.",
     "Slow query performance"),
    ("Batch stored procedure exceeding SLA runtime",
     "Nightly batch stored procedure is exceeding its 2-hour SLA. Query optimizer chose a suboptimal execution plan.",
     "Slow query performance"),
    ("Slow application response traced to database query",
     "APM tool identified a database query contributing 80% of page load time. Query needs index and rewrite.",
     "Slow query performance"),
    ("Statistics out of date causing slow query plan",
     "Query optimizer is using outdated statistics generating a poor execution plan. UPDATE STATISTICS required.",
     "Slow query performance"),

    ("Deadlock detected in order processing tables",
     "SQL Server deadlock graph captured in the error log. Two processes locking member_id in opposite order.",
     "Deadlock detected"),
    ("Deadlock victim error in batch update job",
     "Batch update job is being chosen as deadlock victim. Job needs to be serialised or index hints added.",
     "Deadlock detected"),
    ("Recurring deadlocks on claims table",
     "Claims processing table experiencing deadlocks every 2 minutes during peak hours. Index review required.",
     "Deadlock detected"),
    ("Deadlock between ETL job and OLTP transactions",
     "ETL load job and live OLTP transactions are deadlocking on the staging table. Row-level locking needs review.",
     "Deadlock detected"),
    ("Deadlock trace file captured for analysis",
     "SQL Server deadlock trace captured. Two stored procedures acquiring locks in reverse order need to be serialized.",
     "Deadlock detected"),

    ("SQL Agent backup job failed last night",
     "SQL Agent job for the nightly full backup failed with error 3041. Backup device has insufficient free space.",
     "Backup job failure"),
    ("Database backup not completing within window",
     "Full database backup job is not completing within the maintenance window. Backup compression is not enabled.",
     "Backup job failure"),
    ("Differential backup job failing with VSS error",
     "Differential backup job failing with VSS snapshot error. Windows VSS writer needs to be restarted.",
     "Backup job failure"),
    ("Backup verification job reporting checksum failure",
     "Nightly backup verification is reporting checksum errors. Backup file may be corrupt. New full backup needed.",
     "Backup job failure"),
    ("Log shipping backup job timing out",
     "Log shipping secondary backup job is timing out. Transaction log has grown large due to missed truncation.",
     "Backup job failure"),

    ("Orphaned records found in member table",
     "Data quality audit found 1,200 orphaned records in the member table. Foreign key constraint was disabled during migration.",
     "Data integrity issue"),
    ("Duplicate claim IDs detected in claims table",
     "Claims table contains duplicate claim IDs. Unique constraint was missing from the staging table insert.",
     "Data integrity issue"),
    ("Referential integrity violation on patient records",
     "Patient record deletion failed due to referential integrity violation. Child records exist in claims and billing tables.",
     "Data integrity issue"),
    ("Null values appearing in mandatory fields after migration",
     "Post-migration audit shows null values in columns marked NOT NULL. Insert script had a missing column mapping.",
     "Data integrity issue"),
    ("Data truncation error on string column",
     "Batch insert job failing with data truncation error. Source data exceeds the maximum column length defined in schema.",
     "Data integrity issue"),

    ("Stored procedure returning incorrect totals",
     "The claims_summary_sp stored procedure is returning totals that do not match manual counts. Logic error in WHERE clause.",
     "Stored procedure error"),
    ("SP throwing arithmetic overflow exception",
     "Stored procedure sp_monthly_report throwing ArithmeticOverflowException. DECIMAL column size is too small.",
     "Stored procedure error"),
    ("Stored procedure execution plan causing scan",
     "Stored procedure is using a table scan instead of index seek after statistics update. OPTION RECOMPILE needed.",
     "Stored procedure error"),
    ("Stored procedure failing with permission denied",
     "Stored procedure execution failing with permission denied error after service account password rotation.",
     "Stored procedure error"),
    ("SP parameter sniffing causing inconsistent performance",
     "Stored procedure performance varies wildly due to parameter sniffing. OPTIMIZE FOR UNKNOWN hint needed.",
     "Stored procedure error"),

    ("Database migration rolled back due to constraint error",
     "Schema migration script failed and was rolled back. ALTER TABLE statement violated a NOT NULL constraint.",
     "Database migration failure"),
    ("Post-migration data validation failed",
     "After production migration, data validation checks found 3,000 records with null values in required columns.",
     "Database migration failure"),
    ("Migration script timing out on large table",
     "Migration script times out when altering the claims_archive table (800M rows). Batch approach required.",
     "Database migration failure"),
    ("Schema migration failed due to missing dependent object",
     "Database migration script failed because a view referenced in the migration does not exist in this environment.",
     "Database migration failure"),
    ("Data migration producing incorrect row counts",
     "Post-migration row count validation shows 5% fewer records than source. Data migration script has a filter bug.",
     "Database migration failure"),

    ("SQL Server drive at 95% capacity",
     "D: drive on the production SQL Server is at 95% capacity. Transaction log file has grown unexpectedly.",
     "Disk space alert on DB server"),
    ("TempDB filling up during batch processing",
     "TempDB on production SQL Server filled up during large sort operation causing batch failure.",
     "Disk space alert on DB server"),
    ("Database backup consuming all available disk",
     "Backup files are consuming all available space on the backup drive. Old backups need to be archived.",
     "Disk space alert on DB server"),
    ("SQL Server error log consuming disk space",
     "SQL Server error log has not been cycled in months and is consuming 15 GB of disk space on the OS drive.",
     "Disk space alert on DB server"),
    ("Disk space critically low on database server",
     "Monitoring alert triggered for critically low disk space on DB server. Data files cannot auto-grow further.",
     "Disk space alert on DB server"),

    ("Index fragmentation causing slow queries",
     "Index fragmentation on the claims table has reached 87%. Queries are degrading. Rebuild job needs to run.",
     "Index rebuild needed"),
    ("Clustered index rebuild failing on large table",
     "Clustered index rebuild on member_history (500M rows) is failing due to insufficient log space.",
     "Index rebuild needed"),
    ("Missing index causing full table scans",
     "Query Analyzer recommends adding a composite index on (member_id, claim_date) to eliminate full scans.",
     "Index rebuild needed"),
    ("Index rebuild job not completing before business hours",
     "Nightly index rebuild job is running into business hours impacting performance. Job schedule needs adjustment.",
     "Index rebuild needed"),
    ("Index statistics stale causing poor query plan",
     "Index statistics have not been updated in 30 days. Query optimizer is generating inefficient execution plans.",
     "Index rebuild needed"),

    ("Replication latency exceeding 30 minutes",
     "Transactional replication latency to the reporting replica is 35 minutes. Distribution agent is backed up.",
     "Replication lag"),
    ("Replication agent failing with timeout",
     "Log Reader Agent is timing out when reading from the primary database transaction log. Log is highly fragmented.",
     "Replication lag"),
    ("Subscriber database out of sync with publisher",
     "Reporting subscriber database is out of sync with publisher. Replication snapshot needs to be reapplied.",
     "Replication lag"),
    ("Merge replication conflict causing data divergence",
     "Merge replication conflict resolver chose the wrong winner causing data divergence between nodes.",
     "Replication lag"),
    ("Replication monitor showing distributor backlog",
     "Replication monitor shows distributor has 50,000 undistributed commands. Distribution agent needs to be restarted.",
     "Replication lag"),

    # ── Network Team ─────────────────────────────────────────────────────────
    ("Users unable to connect to VPN from home",
     "Remote users unable to establish VPN connection. Cisco AnyConnect showing authentication failure errors.",
     "VPN connectivity issue"),
    ("VPN split tunnelling causing application failures",
     "VPN split tunnel configuration is routing some application traffic outside the tunnel causing timeouts.",
     "VPN connectivity issue"),
    ("VPN gateway certificate expired",
     "VPN gateway SSL certificate expired causing all client connections to fail with certificate validation error.",
     "VPN connectivity issue"),
    ("VPN client configuration pushed incorrectly",
     "VPN client profile update pushed to endpoints removed the correct gateway address. All remote users affected.",
     "VPN connectivity issue"),
    ("VPN throughput throttled affecting file transfers",
     "VPN throughput is throttled to 10 Mbps causing large EDI file transfers to time out. QoS policy review needed.",
     "VPN connectivity issue"),

    ("High latency reported on internal network",
     "Users on floor 3 reporting 200ms+ latency to internal servers. Network switch port showing high error rate.",
     "Network latency spike"),
    ("Latency spike affecting EDI file transfers",
     "EDI SFTP transfers experiencing latency spikes every 15 minutes. Network monitoring shows burst traffic.",
     "Network latency spike"),
    ("Intermittent packet loss to application servers",
     "Packet loss of 5-8% detected between the web tier and application tier. Physical cable fault suspected.",
     "Network latency spike"),
    ("Network switch port showing high error rate",
     "Managed switch port connected to the database server is showing a high CRC error rate indicating a cable fault.",
     "Network latency spike"),
    ("WAN link saturation causing application timeouts",
     "WAN link between data centre and DR site is saturated. Backup replication is consuming all available bandwidth.",
     "Network latency spike"),

    ("Firewall blocking outbound SFTP traffic",
     "Outbound SFTP connections on port 22 are being blocked by the perimeter firewall. Rule change request needed.",
     "Firewall rule blocking traffic"),
    ("New application blocked by firewall policy",
     "Newly deployed application cannot reach external API endpoint. Firewall egress rule does not permit the destination.",
     "Firewall rule blocking traffic"),
    ("Firewall blocking internal service communication",
     "Microservice A cannot reach microservice B on port 8443. Internal firewall policy does not allow the traffic.",
     "Firewall rule blocking traffic"),
    ("Firewall blocking monitoring agent traffic",
     "Network monitoring agent cannot reach the monitoring server. Firewall is blocking the required UDP port 161.",
     "Firewall rule blocking traffic"),
    ("Firewall rule change caused application outage",
     "Recent firewall rule change removed a previously allowed rule causing the payment application to go offline.",
     "Firewall rule blocking traffic"),

    ("DNS resolution failing for internal hostnames",
     "Applications cannot resolve internal hostnames after DNS server IP address change. Client DNS settings not updated.",
     "DNS resolution failure"),
    ("External DNS lookup timing out",
     "External DNS queries are timing out. Forwarder configuration on internal DNS server is pointing to unreachable IP.",
     "DNS resolution failure"),
    ("DNS caching stale records after server migration",
     "After server migration, DNS cache is returning old IP addresses. TTL values need to be reduced and cache flushed.",
     "DNS resolution failure"),
    ("Split-brain DNS causing resolution inconsistency",
     "Internal and external DNS zones have conflicting records causing inconsistent name resolution for some users.",
     "DNS resolution failure"),
    ("DNS zone transfer failing to secondary server",
     "DNS zone transfer from primary to secondary server is failing. Secondary is serving stale zone data.",
     "DNS resolution failure"),

    ("Load balancer health check failing for app servers",
     "Load balancer health checks are failing for 2 of 4 application servers. Those servers removed from rotation.",
     "Load balancer misconfiguration"),
    ("SSL offloading misconfigured on load balancer",
     "Load balancer SSL offloading is not passing X-Forwarded-Proto header causing application redirect loop.",
     "Load balancer misconfiguration"),
    ("Sticky session configuration causing uneven load",
     "Load balancer sticky session configuration is pinning 80% of traffic to one server causing overload.",
     "Load balancer misconfiguration"),
    ("Load balancer not respecting server weights",
     "Load balancer weight configuration is not distributing traffic proportionally. All requests going to one node.",
     "Load balancer misconfiguration"),
    ("Load balancer timeout too short for long requests",
     "Load balancer is terminating long-running API requests before they complete. Idle timeout needs to be increased.",
     "Load balancer misconfiguration"),

    # ── Access Team ───────────────────────────────────────────────────────────
    ("User locked out of Active Directory account",
     "User account locked out after multiple failed login attempts. Account needs to be unlocked in Active Directory.",
     "User account locked"),
    ("Service account locked causing application failure",
     "Application service account was locked out overnight causing batch jobs to fail. Password complexity issue.",
     "User account locked"),
    ("Mass account lockout after password policy change",
     "Password policy change caused 50 user accounts to lock simultaneously. Policy rollback may be needed.",
     "User account locked"),
    ("Account locked due to stale cached credentials",
     "User account is locking repeatedly due to stale cached credentials on a workstation. Cache must be cleared.",
     "User account locked"),
    ("Admin account locked after after-hours login attempt",
     "Privileged admin account locked after multiple failed login attempts detected outside business hours.",
     "User account locked"),

    ("User requesting password reset for AD account",
     "User forgot Active Directory password and is locked out. Identity verification completed. Reset required.",
     "Password reset request"),
    ("Application service account password expiry",
     "Service account password expired causing IIS application pool to fail. Password needs to be reset and updated.",
     "Password reset request"),
    ("Bulk password reset required after security event",
     "Following a phishing incident, 30 user accounts require immediate password reset per security policy.",
     "Password reset request"),
    ("Self-service password reset portal not working",
     "Users cannot reset their own passwords via the self-service portal. Portal is showing a configuration error.",
     "Password reset request"),
    ("Password reset not syncing to Azure AD",
     "On-premises password reset is not syncing to Azure Active Directory. Azure AD Connect sync is in error state.",
     "Password reset request"),

    ("User cannot access shared network drive",
     "User receiving Access Denied error when accessing the Finance shared drive. Group membership needs to be verified.",
     "Permission denied on folder"),
    ("Permission issue after folder restructure",
     "After SharePoint folder restructure, users in the Claims team cannot access their document library.",
     "Permission denied on folder"),
    ("New employee denied access to project folder",
     "New hire cannot access the project shared folder. Access request approved but group assignment not applied.",
     "Permission denied on folder"),
    ("User receiving access denied on application module",
     "User receiving access denied error when opening the billing module. Role assignment was removed during last audit.",
     "Permission denied on folder"),
    ("Shared mailbox permission removed accidentally",
     "User lost access to a shared mailbox after an automated access review script removed the delegation incorrectly.",
     "Permission denied on folder"),

    ("MFA not working for remote users",
     "Remote users unable to complete MFA challenge. Authenticator app not receiving push notifications.",
     "MFA not working"),
    ("MFA bypass not available for legacy application",
     "Legacy application does not support MFA. Conditional access policy is blocking all users from logging in.",
     "MFA not working"),
    ("Microsoft Authenticator token out of sync",
     "Multiple users reporting MFA tokens are out of sync. Time drift on user devices causing token mismatch.",
     "MFA not working"),
    ("MFA enrollment failing for new user",
     "New employee unable to complete MFA enrollment. Conditional access policy is blocking the registration endpoint.",
     "MFA not working"),
    ("MFA prompt appearing for internal network users",
     "Users on the corporate network are being prompted for MFA unexpectedly. Trusted IP range is not configured.",
     "MFA not working"),

    ("New employee needs access to all business systems",
     "New employee starting Monday requires access to email, Teams, SharePoint, and HR portal. Manager approved.",
     "New user onboarding access"),
    ("Contractor access provisioning request",
     "External contractor needs time-limited access to the development environment and JIRA project.",
     "New user onboarding access"),
    ("New analyst requires read-only database access",
     "New business analyst needs read-only access to the reporting database. Access provisioning form submitted.",
     "New user onboarding access"),
    ("Transferred employee needs access updated",
     "Employee transferred to new department requires removal of old access and provisioning of new system permissions.",
     "New user onboarding access"),
    ("Intern account setup for summer placement",
     "Summer intern joining next week requires temporary accounts for email, SharePoint and the test environment.",
     "New user onboarding access"),

    # ── Security Team ─────────────────────────────────────────────────────────
    ("Suspicious login from unknown IP address",
     "User account showing successful login from an IP address in an unexpected geographic location. Account under review.",
     "Suspicious login attempt"),
    ("Multiple failed login attempts on admin account",
     "Admin account experiencing brute force login attempts from external IP. Account temporarily suspended.",
     "Suspicious login attempt"),
    ("After-hours login detected on privileged account",
     "SIEM alert triggered for after-hours login on a privileged service account. User did not initiate the session.",
     "Suspicious login attempt"),
    ("Credential stuffing attack detected on portal",
     "WAF detected a credential stuffing attack on the patient portal. Rate limiting and CAPTCHA should be enabled.",
     "Suspicious login attempt"),
    ("Impossible travel login alert triggered",
     "SIEM impossible travel alert fired for a user account logging in from two countries within 30 minutes.",
     "Suspicious login attempt"),

    ("Malware detected on finance department laptop",
     "Endpoint protection flagged Trojan.GenericKD on a finance department laptop. Device quarantined and isolated.",
     "Malware detected on endpoint"),
    ("Ransomware alert triggered on file server",
     "Endpoint protection triggered a ransomware alert on the file server. Mass file encryption activity detected.",
     "Malware detected on endpoint"),
    ("Suspicious executable blocked on workstation",
     "Endpoint agent blocked execution of an unknown process attempting to modify system registry keys.",
     "Malware detected on endpoint"),
    ("Adware installed on user laptop without consent",
     "User reported unwanted pop-up ads appearing continuously. Endpoint scan confirmed adware installation.",
     "Malware detected on endpoint"),
    ("Crypto-mining malware detected on server",
     "Server CPU utilisation spiked to 100% overnight. Endpoint security tool identified crypto-mining process.",
     "Malware detected on endpoint"),

    ("User reported phishing email with malicious link",
     "User received an email impersonating IT helpdesk asking for credentials. Email contains malicious URL.",
     "Phishing email reported"),
    ("Spear phishing campaign targeting executives",
     "Three executives received targeted phishing emails impersonating the CEO requesting wire transfers.",
     "Phishing email reported"),
    ("Phishing email bypassed spam filter",
     "A convincing phishing email bypassed the email gateway spam filter and reached 20 mailboxes.",
     "Phishing email reported"),
    ("Phishing link clicked by multiple users",
     "Five users clicked a phishing link in a spoofed HR email. Incident response process initiated immediately.",
     "Phishing email reported"),
    ("Vishing call attempting to obtain credentials",
     "User received a phone call from someone impersonating IT support requesting their AD credentials. Reported to security.",
     "Phishing email reported"),

    ("Critical security patch not deployed within SLA",
     "MS-CVE-2026-1234 critical patch has not been deployed to 15 servers within the required 72-hour SLA.",
     "Security patch deployment"),
    ("Patch deployment causing application failure",
     "Recent Windows security patch broke a legacy .NET application. Rollback plan needed for affected servers.",
     "Security patch deployment"),
    ("Patch compliance below threshold for audit",
     "Monthly patch compliance report shows 23% of endpoints are below the required 95% patch compliance threshold.",
     "Security patch deployment"),
    ("Emergency patch required for zero-day vulnerability",
     "Vendor released an emergency patch for a zero-day vulnerability being actively exploited. Immediate deployment needed.",
     "Security patch deployment"),
    ("Patch rollback required after application failure",
     "Recent security patch broke a production application. Patch must be rolled back and the vendor notified.",
     "Security patch deployment"),

    ("Audit finding: excessive admin account privileges",
     "External audit identified 12 users with admin rights who do not require elevated access. Access review needed.",
     "Compliance audit finding"),
    ("SOX audit failure: no segregation of duties",
     "SOX audit found a user who has both transaction entry and approval rights. Access must be separated immediately.",
     "Compliance audit finding"),
    ("HIPAA audit finding: unencrypted PHI on laptop",
     "Compliance audit found unencrypted protected health information stored on a user laptop. Encryption required.",
     "Compliance audit finding"),
    ("PCI DSS audit finding: card data in plain text logs",
     "PCI DSS audit found card holder data appearing in plain text application logs. Log masking must be implemented.",
     "Compliance audit finding"),
    ("Audit finding: missing evidence for access reviews",
     "Annual compliance audit could not locate evidence of quarterly access reviews for privileged accounts.",
     "Compliance audit finding"),
]

# ---------------------------------------------------------------------------

def build_training_excel(out_path: Path) -> None:
    df = pd.DataFrame(ROWS, columns=["Summary", "Description", "Category"])

    # Sanity check
    counts = df["Category"].value_counts()
    categories_with_few = counts[counts < 2]
    if not categories_with_few.empty:
        print(f"WARNING — these categories have < 2 samples (stratified split may fail):")
        print(categories_with_few.to_string())

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with pd.ExcelWriter(str(out_path), engine="openpyxl") as writer:
        df.to_excel(writer, index=False, sheet_name="Tickets")

    print(f"Saved → {out_path}")
    print(f"Total rows : {len(df)}")
    print(f"Categories : {df['Category'].nunique()}")
    print(f"\nSamples per category:")
    print(counts.to_string())


if __name__ == "__main__":
    out = Path(__file__).resolve().parents[1] / "data" / "sample_tickets.xlsx"
    build_training_excel(out)
